const foto = [
    {   img : 'img/01.jpg',
        titolo: 'Svezia',
        testo : ' del testo a caso',
    },
    {   img : 'img/02.jpg',
        titolo: 'Svezia',
        testo : ' del testo a caso',
    },
    {   img : 'img/02.jpg',
        titolo: 'Svezia',
        testo : ' del testo a caso',
    },
    {   img : 'img/03.jpg',
        titolo: 'Svezia',
        testo : ' del testo a caso',
    },
    {   img : 'img/04.jpg',
        titolo: 'Svezia',
        testo : ' del testo a caso',
    },
]